### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by moedong** [nuxt-community/koa-template#38]
DONE  Compiled successfully in 655ms                                   11:59:05

E:\node\koa-nuxt\node_modules\_nuxt@1.4.0@nuxt\lib\core\middleware\nuxt.js:72
      const policies = this.options.render.csp.policies ? {...this.options.rende
r.csp.policies} : null
                                                           ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\node\koa-nuxt\node_modules\_nuxt@1.4.0@nuxt\lib\co
re\renderer.js:19:24)

**Comment by chanlito** [comment]
Can you tell us what's your node.js version?

**Comment by moedong** [comment]
my node.js version is too low. i update node.js to version 8.11.1. it's ok now，Thanks
